[package]
name = "svfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.20"
toml = "1.1.4"
tree-sitter = "0.26.12"
tree-sitter-systemverilog = "0.4.0"
